### ISSUE TITLE
problem when parsing time strings

### ISSUE THREAD

**Issue by mraspaud** [pytroll/trollsift#1]
Hi,

Just stumbled upon a problem when parsing a timestring with tens of seconds in it. Works fine with strptime, but not in trollsift:

``` python
>>> fname = "npp_20141017_1134583.nc"

>>> datetime.datetime.strptime(fname, "npp_%Y%m%d_%H%M%S%f.nc")
datetime.datetime(2014, 10, 17, 11, 34, 58, 300000)

>>> parse("npp_{start_time:%Y%m%d_%H%M%S%f}.nc", fname)
[...] ValueError:
```

Any way to fix that ?

**Comment by pnuu** [comment]
The parsing with `%f` has been fixed/implenmented, closing issue.
