### ISSUE TITLE
Different parsing allignment behaviour between 0.2.* and 0.3.*

### ISSUE THREAD

**Issue by egremmer** [pytroll/trollsift#18]
Trying to parse parts of a filename and store the remainder in the last part. The remaining parts are alligned differently between versions.

The following code illustrates the problem:
```
import trollsift

fname = 'Amplitude_VH_db_S1A_IW_GRDH_1SDV_20160528T171628_20160528T171653_011462_011752_0EED.tif'
template_parts = ['{band_type}',
                  '{polarization_extracted}',
                  '{unit}',
                  '{s1_fname}']
template = '_'.join(template_parts)
p = trollsift.Parser(template)

print(p.parse(fname))
```
**Version 0.2.1**
`{'s1_fname': 'S1A_IW_GRDH_1SDV_20160528T171628_20160528T171653_011462_011752_0EED.tif', 'unit': 'db', 'polarization_extracted': 'VH', 'band_type': 'Amplitude'}`

**Version 0.3.1**
`{'band_type': 'Amplitude_VH_db_S1A_IW_GRDH_1SDV_20160528T171628_20160528T171653', 'polarization_extracted': '011462', 'unit': '011752', 's1_fname': '0EED.tif'}`

It seems like the direction of parsing has changed, thus producing inconsistent results. Is there a possible solution/workaround to get the old alignment direction in version 0.3.*?
Thanks in advance.

**Comment by mraspaud** [comment]
@djhoese Could this be cause be the conversion to re ?

**Comment by mraspaud** [comment]
@egremmer thanks you very much for the clear and concise bug report ! We will look into this shortly.

**Comment by djhoese** [comment]
This is most likely caused by my changes and using `re`, but this is also unexpected. The fact that it wasn't caught by tests means we aren't testing everything we should be. I will say that I think it is *supposed* to be have like the first version and am actually surprised at the output you are seeing. It's Thanksgiving this week so I probably won't be able to get to this until next week.

**Comment by djhoese** [comment]
Ok so I was able to reproduce this and have a semi-easy fix by telling the regular expression to be non-greedy (`.*?`). However, I'm a little worried this might be a problem in other use cases. However, it doesn't break any tests....so :man_shrugging:

**Comment by cpaulik** [comment]
Would be nice to get this fix into a release if possible. Thanks.

**Comment by djhoese** [comment]
:man_facepalming: Sorry, forgot about this. I'll try to make a release later today.

**Comment by djhoese** [comment]
Version 0.3.4 git tag has been created, PyPI builds starting. Conda-forge builds will be available by the end of the day most likely. Thanks for reminding me @cpaulik!
