### ISSUE TITLE
Bug when parsing leap day when you dont have year

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/trollsift#23]
I receive some NWP files from ECMWF. The file name is like this `N2D02281200022900001` where you have analysis time and forcast time without year. When you have a leap day trollsift Parser validate fails. See example bellow. (tested on both 2.7 trollsift 0.2.0 and 3.5 trollsift 0.3.2)
```
PYTHONPATH=/software//pytroll/lib/python3.5/site-packages/ python
Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from trollsift import Parser
>>> parser = Parser("{ecmwf_prefix:3s}{analysis_time:%m%d%H%M}{forecast_time:%m%d%H%M}{end:1s}")
>>> parser.validate("N2D02281200022900001")
False
>>> parser.validate("N2D02281200022800001")
True
```

**Comment by TAlonglong** [comment]
Not a trollsift bug nor python bug.

https://bugs.python.org/issue26460

**Comment by djhoese** [comment]
Ha that's fun.

**Comment by djhoese** [comment]
So can we close this? The python bug report points to new documentation that talks about how this is unsupported (asking for Feb 29 without a year will fail).

I'm not sure there is an easy way to solve this...who doesn't put a year in their filename?

**Comment by TAlonglong** [comment]
ECMWF does not.

Yes I will close this
