### ISSUE TITLE
Problems with padding syntax

### ISSUE THREAD

**Issue by paulovcmedeiros** [pytroll/trollsift#30]
Hi,

I'm facing some issues parsing strings with trollsift using padding syntax. For example, the code below raises `ValueError: Invalid format specification: '\_\<8'`.

```python
import trollsift

format_spec = "{foo}/{bar:_<8}"
my_str = format_spec.format(foo="baz", bar="qux")

parser = trollsift.Parser(format_spec)
data = parser.parse(my_str)
```

Do you have any idea how to approach this?

Many thanks in advance.
Best wishes,
Paulo.

**Comment by djhoese** [comment]
I'm not sure the parser supports padding syntax. Was there an example you found of it being used in the trollsift docs? I'm not sure what it would take to add support for it if it isn't already implemented.

**Comment by paulovcmedeiros** [comment]
Thanks for the quick reply!

No, there were no examples in the docs. I stumbled upon this while parsing some [trollmoves](https://github.com/pytroll/trollmoves) log messages according to a few specific formats.

**Comment by paulovcmedeiros** [comment]
Just adding a comment, as I stumbled upon this issue again today: While ``format_spec = "{foo}/{bar:_<8}"`` works only when composing,  `format_spec = "{foo}/{bar:_<8s}"` works both for composing and for parsing.

**Comment by djhoese** [comment]
@paulovcmedeiros Maybe we could add a warning when padding syntax is detected during parsing? Would you be able to create a pull request for this?
