### ISSUE TITLE
Trollsift doesn't parse hex numbers

### ISSUE THREAD

**Issue by mraspaud** [pytroll/trollsift#34]
Parsing hex numbers produces strings.

```python
In [14]: text = "03e8_welcome"

In [15]: pattern = "{number:04x}_{something}"

In [16]: parse(pattern, text)
Out[16]: {'number': '03e8', 'something': 'welcome'}
```
Format (and compose) on the other hand work as expected:
```python
In [17]: pattern.format(number=1000, something="hej")
Out[17]: '03e8_hej'
```

**Comment by djhoese** [comment]
It looks like we're missing the handling of converting this to a number here:

https://github.com/pytroll/trollsift/blob/77c3efcc58eda33ae8ffa3579db811912e09de6a/trollsift/parser.py#L389-L400

The assumption is that only `d` and floating-like formats need to be converted from string to number:

https://github.com/pytroll/trollsift/blob/main/trollsift/parser.py#L168

I guess the `d` case needs to be updated to handle `x`.

**Comment by mraspaud** [comment]
I think we need to add more than `x`. According to https://docs.python.org/3/library/string.html#format-specification-mini-language, valid integer presentation types are `b`, `d`, `o`, `x`, `X`, `n` (and possibly `c`)
