### ISSUE TITLE
Add custom string formatter for lower/upper support

### ISSUE THREAD

**Issue by djhoese** [pytroll/trollsift#5]
See https://github.com/pytroll/satpy/issues/417

I'd like to add a custom formatter so that someone could call `upper` and `lower` and possibly other operations on a string to help "standardize" filenames the way users want without having to directly modify the attributes/parameters going in to the string formatting.

**Comment by djhoese** [comment]
Skimming the `Parser` code which is used in satpy to accomplish this: we'll have to note that these functions are only used for formatting the string and do not affect the glob/pattern matching functionality. @pnuu, sound good?

**Comment by pnuu** [comment]
Yep, sounds right.
